### ISSUE TITLE
Failed to accept the invitation

### ISSUE THREAD

**Issue by lrajula** [QuiNovas/terraform-aws-guardduty#17]
Hi, 
 Terrafrom script is failed at accept invitation. Here master is enabled, invitations are sending to members but while accepting it is failed due to unable to find the member invitation id.

**Below is output including error:**

aws_guardduty_detector.master: Creating...
aws_guardduty_detector.master: Creation complete after 2s [id=12b77f36ee2355aa3fc04490e7522a21]
aws_guardduty_invite_accepter.member_accepter[0]: Creating...
aws_guardduty_member.members[0]: Creating...
aws_guardduty_member.members[0]: Creation complete after 3s [id=12b77f36ee2355aa3fc04490e7522a21:778340753754]
aws_guardduty_invite_accepter.member_accepter[0]: Still creating... [10s elapsed]
aws_guardduty_invite_accepter.member_accepter[0]: Still creating... [20s elapsed]
aws_guardduty_invite_accepter.member_accepter[0]: Still creating... [30s elapsed]
aws_guardduty_invite_accepter.member_accepter[0]: Still creating... [40s elapsed]
aws_guardduty_invite_accepter.member_accepter[0]: Still creating... [50s elapsed]

**Error: error listing GuardDuty Invitations: unable to find pending GuardDuty Invitation for detector ID (12b77f36ee2355aa3fc04490e7522a21) from master account ID (180557658610)**

  on main.tf line 23, in resource "aws_guardduty_invite_accepter" "member_accepter":
  23: resource "aws_guardduty_invite_accepter" "member_accepter" {

Could you please help on this.

**Here is my terraform,**

provider "aws" {
  region  = "${var.aws_region}"
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
}

//master
resource "aws_guardduty_detector" "master" {
  enable = true
}

resource "aws_guardduty_member" "members" {
  count = "${length(var.member_account_ids)}"
  detector_id = "${aws_guardduty_detector.master.id}"
  account_id = "${element(var.member_account_ids, count.index)}"
  email = "${element(var.member_account_emails, count.index)}"
  invite = true
  invitation_message = "GuardDuty Invite - Please accept this invitation if you are expecting it."
}

resource "aws_guardduty_invite_accepter" "member_accepter" {

  count             = var.accept_invite && length(var.aws_master_account_id) > 0 ? 1 : 0
  detector_id       = aws_guardduty_detector.master.id
  master_account_id = var.aws_master_account_id
}

**Comment by lrajula** [comment]
Can anyone help on the above  issue ?

**Comment by vchinnakotla** [comment]
@lrajula 
I see that you are trying to use same guardduty account as a _master_ (which can invite other accounts) and a _member of master_ (cannot invite other accounts). It can only be either of them.

Instead of using the above code, you can use module like below.
Lets say you want AWS Account _123_ as Master and Account _789_ Member

This code to be run on Account _123_
```
module "guardduty_master" {

  member_list = [
    {
      account_id   = "789"
      member_email = "account789@test.com"
      invite       = "true"
    }
  ]

  source  = "QuiNovas/guardduty/aws"
  version = "3.0.0"
}
```


This code to be run on Account _789_
```
module "guardduty_member" {
  accept_invite  = true
  accepter_master_account_id  = "123"
  source   = "QuiNovas/guardduty/aws"
  version   = "3.0.0"
}
```

**Comment by vchinnakotla** [comment]
@lrajula I am closing the issue, I guess the above comments would help you to fix your code.

**Comment by lrajula** [comment]
Yes, it is working as expected. Thank you so much @vchinnakotla !!
