### ISSUE TITLE
Add default for account_name using caller_identity datasource

### ISSUE THREAD

**Issue by JoshiiSinfield** [QuiNovas/terraform-aws-guardduty#7]
Hi,

It'd be great to use the caller_identity resource to set default value for account_name if none specified.

We're using Terragrunt to run our modules, and not having to hard code the account number in an extra place would be helpful.

I'll push a PR up.

Cheers,
Josh

**Comment by JoshiiSinfield** [comment]
PR #8 pushed to address this.

**Comment by vchinnakotla** [comment]
pulled the changes in.
